#!/bin/make
#
# hash - makefile for FNV hash tools
#
# @(#) $Revision: 3.21 $
# @(#) $Id: Makefile,v 3.21 2003/10/03 20:36:26 chongo Exp chongo $
# @(#) $Source: /usr/local/src/cmd/fnv/RCS/Makefile,v $
#
# See:
#	http://www.isthe.com/chongo/tech/comp/fnv/index.html
#
# for the most up to date copy of this code and the FNV hash home page.
#
# Please do not copyright this code.  This code is in the public domain.
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# By:
#	chongo <Landon Curt Noll> /\oo/\
#	http://www.isthe.com/chongo/
#
# Share and Enjoy!	:-)

# make tools
#
SHELL= /bin/sh
CFLAGS= -O3 -g3
#CFLAGS= -O2 -g3
#CC= cc
AR= ar
TAR= tar
EGREP= egrep
GZIP_BIN= gzip
INSTALL= install

# If your system needs ranlib use:
#	RANLIB= ranlib
# otherwise use:
#	RANLIB= :
#
#RANLIB= ranlib
RANLIB= :

# where to install things
#
DESTBIN= /usr/local/bin
DESTLIB= /usr/local/lib
DESTINC= /usr/local/include
# NOTE: Lines with WWW in them are removed from the shipped Makefile
WWW= /web/isthe/chroot/html/chongo/src/fnv

# what to build
#
SRC=	hash_32.c hash_32a.c hash_64.c hash_64a.c \
	fnv32.c fnv64.c \
	have_ulong64.c test_fnv.c
HSRC=	fnv.h \
	longlong.h
ALL=	${SRC} ${HSRC} \
	README Makefile
PROGS=	fnv032 fnv064 fnv132 fnv164 fnv1a32 fnv1a64
OBSOLETE_PROGS=	fnv0_32 fnv0_64 fnv1_32 fnv1_64 fnv1a_32 fnv1a_64
LIBS=	libfnv.a
LIBOBJ=	hash_32.o hash_64.o hash_32a.o hash_64a.o test_fnv.o
OTHEROBJ= fnv32.o fnv64.o
TARGETS= ${LIBOBJ} ${LIBS} ${PROGS}

# default rule
#
all: ${TARGETS}

# things to build
#
hash_32.o: hash_32.c longlong.h fnv.h
	${CC} ${CFLAGS} hash_32.c -c

hash_64.o: hash_64.c longlong.h fnv.h
	${CC} ${CFLAGS} hash_64.c -c

hash_32a.o: hash_32a.c longlong.h fnv.h
	${CC} ${CFLAGS} hash_32a.c -c

hash_64a.o: hash_64a.c longlong.h fnv.h
	${CC} ${CFLAGS} hash_64a.c -c

text_fnv.o: text_fnv.c longlong.h fnv.h
	${CC} ${CFLAGS} text_fnv.c -c

libfnv.a: ${LIBOBJ}
	rm -f $@
	${AR} rv $@ ${LIBOBJ}
	${RANLIB} $@

fnv32.o: fnv32.c longlong.h fnv.h
	${CC} ${CFLAGS} fnv32.c -c

fnv032: fnv32.o libfnv.a
	${CC} fnv32.o libfnv.a -o fnv032

fnv64.o: fnv64.c longlong.h fnv.h
	${CC} ${CFLAGS} fnv64.c -c

fnv064: fnv64.o libfnv.a
	${CC} fnv64.o libfnv.a -o fnv064

fnv132: fnv032
	-rm -f $@
	-cp -f $? $@

fnv1a32: fnv032
	-rm -f $@
	-cp -f $? $@

fnv164: fnv064
	-rm -f $@
	-cp -f $? $@

fnv1a64: fnv064
	-rm -f $@
	-cp -f $? $@

longlong.h: have_ulong64.c Makefile
	-@rm -f have_ulong64 have_ulong64.o ll_tmp longlong.h
	@echo 'forming longlong.h'
	@echo '/*' > longlong.h
	@echo ' * DO NOT EDIT -- generated by the Makefile' >> longlong.h
	@echo ' */' >> longlong.h
	@echo '' >> longlong.h
	@echo '#if !defined(__LONGLONG_H__)' >> longlong.h
	@echo '#define __LONGLONG_H__' >> longlong.h
	@echo '' >> longlong.h
	@echo '/* do we have/want to use a long long type? */' >> longlong.h
	-@rm -f have_ulong64.o have_ulong64
	-@${CC} ${CFLAGS} have_ulong64.c -c 2>/dev/null; true
	-@${CC} ${CFLAGS} have_ulong64.o -o have_ulong64 2>/dev/null; true
	-@${SHELL} -c "./have_ulong64 > ll_tmp 2>/dev/null" \
	    >/dev/null 2>&1; true
	-@if [ -s ll_tmp ]; then \
	    cat ll_tmp >> longlong.h; \
	else \
	    echo '#undef HAVE_64BIT_LONG_LONG	/* no */' >> longlong.h; \
	fi
	@echo '' >> longlong.h
	@echo '#endif /* !__LONGLONG_H__ */' >> longlong.h
	-@rm -f have_ulong64 have_ulong64.o ll_tmp
	@echo 'longlong.h formed'

# utilities
#
install: all
	-@if [ -d "${DESTBIN}" ]; then \
	    echo "	mkdir -p ${DESTBIN}"; \
	    mkdir -p ${DESTBIN}; \
	fi
	-@if [ -d "${DESTLIB}" ]; then \
	    echo "	mkdir -p ${DESTLIB}"; \
	    mkdir -p ${DESTLIB}; \
	fi
	-@if [ -d "${DESTINC}" ]; then \
	    echo "	mkdir -p ${DESTINC}"; \
	    mkdir -p ${DESTINC}; \
	fi
	${INSTALL} -m 0755 ${PROGS} ${DESTBIN}
	${INSTALL} -m 0644 ${LIBS} ${DESTLIB}
	${RANLIB} ${DESTLIB}/libfnv.a
	${INSTALL} -m 0644 ${HSRC} ${DESTINC}
	@# NOTE: Lines with WWW in them are removed from the shipped Makefile
	-@if [ -d ${WWW} ]; then \
	    echo "rm -f Makefile.ship";			: WWW; \
	    rm -f Makefile.ship;			: WWW; \
	    echo "${EGREP} -v WWW Makefile > Makefile.ship"; 	: WWW; \
	    ${EGREP} -v WWW Makefile > Makefile.ship; 	: WWW; \
	    echo "rm -f Makefile.save";			: WWW; \
	    rm -f Makefile.save;			: WWW; \
	    echo "ln Makefile Makefile.save";		: WWW; \
	    ln Makefile Makefile.save;			: WWW; \
	    echo "cp -f Makefile.ship Makefile";	: WWW; \
	    cp -f Makefile.ship Makefile;		: WWW; \
	    echo "${TAR} -cf - ${ALL} | ${GZIP_BIN} --best > fnv_hash.tar.gz";: WWW; \
	    ${TAR} -cf - ${ALL} | ${GZIP_BIN} --best > fnv_hash.tar.gz;: WWW; \
	    echo "${INSTALL} -m 0644 fnv_hash.tar.gz ${ALL} ${WWW}"; \
	    ${INSTALL} -m 0644 fnv_hash.tar.gz ${ALL} ${WWW}; \
	    echo "mv -f Makefile.save Makefile";	: WWW; \
	    mv -f Makefile.save Makefile;		: WWW; \
	    echo "rm -f fnv_hash.tar.gz Makefile.ship";	: WWW; \
	    rm -f fnv_hash.tar.gz Makefile.ship;	: WWW; \
	fi;						: WWW
	@# remove osolete programs
	for i in ${OBSOLETE_PROGS}; do \
	    if [ -f "${DESTBIN}/$$i" ]; then \
	        echo "rm -f ${DESTBIN}/$$i"; \
		rm -f "${DESTBIN}/$$i"; \
	    fi; \
	done

clean:
	-rm -f have_ulong64 have_ulong64.o ll_tmp ll_tmp2 longlong.h
	-rm -f ${LIBOBJ}
	-rm -f ${OTHEROBJ}
	-rm -f fnv_hash.tar.gz Makefile.ship	# WWW

clobber: clean
	-rm -f ${TARGETS}
	-rm -f ${OBSOLETE_PROGS}
	-rm -f lltmp lltmp2 fnv_vector.c

fnv_vector.c: ${PROGS}
	-rm -f $@
	echo '/* start of output generated by make $@ */' >> $@
	echo '/* FNV-0 32 bit test vectors */' >> $@
	./fnv032 -t 0 >> $@
	echo '' >> $@
	echo '/* FNV-1 32 bit test vectors */' >> $@
	./fnv132 -t 0 >> $@
	echo '' >> $@
	echo '/* FNV-1a 32 bit test vectors */' >> $@
	./fnv1a32 -t 0 >> $@
	echo '' >> $@
	echo '/* FNV-0 64 bit test vectors */' >> $@
	./fnv064 -t 0 >> $@
	echo '' >> $@
	echo '/* FNV-1 64 bit test vectors */' >> $@
	./fnv164 -t 0 >> $@
	echo '' >> $@
	echo '/* FNV-1a 64 bit test vectors */' >> $@
	./fnv1a64 -t 0 >> $@
	echo '/* end of output generated by make $@ */' >> $@

check: all
	@echo
	@echo "	These tests should not print an un-indented hash value:"
	@echo
	@echo "	fnv032 -s hi == 0x6800a3d1"
	-@./fnv032 -s hi | ${EGREP} -v 0x6800a3d1; /bin/true
	@echo "	fnv032 -s hello == 0xec6d6be8"
	-@./fnv032 -s hello | ${EGREP} -v 0xec6d6be8; /bin/true
	@echo "	fnv032 -s curds and whey == 0x4a83403b"
	-@./fnv032 -s curds and whey | ${EGREP} -v 0x4a83403b; /bin/true
	@echo "	fnv064 -s hi == 0x000068000000b0d1"
	-@./fnv064 -s hi | ${EGREP} -v 0x000068000000b0d1; /bin/true
	@echo "	fnv064 -s hello == 0x3fa86e63bc7d03c8"
	-@./fnv064 -s hello | ${EGREP} -v 0x3fa86e63bc7d03c8; /bin/true
	@echo "	fnv064 -s curds and whey == 0x09d2b4132bd1333b"
	-@./fnv064 -s curds and whey | ${EGREP} -v 0x09d2b4132bd1333b;/bin/true
	-@rm -f lltmp lltmp2
	-@echo line 1 > lltmp
	-@echo line 2 >> lltmp
	-@echo line 3 >> lltmp
	@echo '	echo "line 1\\nline 2\\nline 3" > lltmp'
	@echo "	dd if=/dev/zero bs=1024k count=4 of=lltmp2 >/dev/null 2>&1"
	-@dd if=/dev/zero bs=1024k count=4 of=lltmp2 >/dev/null 2>&1
	@echo "	fnv032 < lltmp == 0x1fad81d0"
	-@./fnv032 < lltmp | ${EGREP} -v 0x1fad81d0; /bin/true
	@echo "	fnv064 < lltmp == 0xa8cf5b7784759250"
	-@./fnv064 < lltmp | ${EGREP} -v 0xa8cf5b7784759250; /bin/true
	@echo "	fnv032 < lltmp2 == 0x00000000"
	-@./fnv032 < lltmp2 | ${EGREP} -v 0x00000000; /bin/true
	@echo "	fnv064 < lltmp2 == 0x0000000000000000"
	-@./fnv064 < lltmp2 | ${EGREP} -v 0x0000000000000000; /bin/true
	@echo "	fnv032 lltmp == 0x1fad81d0"
	-@./fnv032 lltmp | ${EGREP} -v 0x1fad81d0; /bin/true
	@echo "	fnv064 lltmp == 0xa8cf5b7784759250"
	-@./fnv064 lltmp | ${EGREP} -v 0xa8cf5b7784759250; /bin/true
	@echo "	fnv032 lltmp2 == 0x00000000"
	-@./fnv032 lltmp2 | ${EGREP} -v 0x00000000; /bin/true
	@echo "	fnv064 lltmp2 == 0x0000000000000000"
	-@./fnv064 lltmp2 | ${EGREP} -v 0x0000000000000000; /bin/true
	@echo "	fnv032 lltmp lltmp == 0xc500fd20"
	-@./fnv032 lltmp lltmp | ${EGREP} -v 0xc500fd20; /bin/true
	@echo "	fnv064 lltmp lltmp == 0x3c8b9c3715fc1920"
	-@./fnv064 lltmp lltmp | ${EGREP} -v 0x3c8b9c3715fc1920; /bin/true
	@echo "	fnv032 lltmp lltmp2 == 0x6fad81d0"
	-@./fnv032 lltmp lltmp2 | ${EGREP} -v 0x6fad81d0; /bin/true
	@echo "	fnv064 lltmp lltmp2 == 0x29a78f5dd4759250"
	-@./fnv064 lltmp lltmp2 | ${EGREP} -v 0x29a78f5dd4759250; /bin/true
	@echo "	fnv032 lltmp2 lltmp == 0x1fad81d0"
	-@./fnv032 lltmp2 lltmp | ${EGREP} -v 0x1fad81d0; /bin/true
	@echo "	fnv064 lltmp2 lltmp == 0xa8cf5b7784759250"
	-@./fnv064 lltmp2 lltmp | ${EGREP} -v 0xa8cf5b7784759250; /bin/true
	@echo "	fnv032 lltmp2 lltmp2 == 0x00000000"
	-@./fnv032 lltmp2 lltmp2 | ${EGREP} -v 0x00000000; /bin/true
	@echo "	fnv064 lltmp2 lltmp2 == 0x0000000000000000"
	-@./fnv064 lltmp2 lltmp2 | ${EGREP} -v 0x0000000000000000; /bin/true
	@echo
	@echo "	fnv132 -s hi == 0x6977223c"
	-@./fnv132 -s hi | ${EGREP} -v 0x6977223c; /bin/true
	@echo "	fnv132 -s hello == 0xb6fa7167"
	-@./fnv132 -s hello | ${EGREP} -v 0xb6fa7167; /bin/true
	@echo "	fnv132 -s curds and whey == 0x08ebf912"
	-@./fnv132 -s curds and whey | ${EGREP} -v 0x08ebf912; /bin/true
	@echo "	fnv164 -s hi == 0x08326007b4eb2b9c"
	-@./fnv164 -s hi | ${EGREP} -v 0x08326007b4eb2b9c; /bin/true
	@echo "	fnv164 -s hello == 0x7b495389bdbdd4c7"
	-@./fnv164 -s hello | ${EGREP} -v 0x7b495389bdbdd4c7; /bin/true
	@echo "	fnv164 -s curds and whey == 0x795ad7b2d9a7dc72"
	-@./fnv164 -s curds and whey | ${EGREP} -v 0x795ad7b2d9a7dc72;/bin/true
	@echo "	fnv132 < lltmp == 0xb8cbeb33"
	-@./fnv132 < lltmp | ${EGREP} -v 0xb8cbeb33; /bin/true
	@echo "	fnv164 < lltmp == 0x79dcad190c3291b3"
	-@./fnv164 < lltmp | ${EGREP} -v 0x79dcad190c3291b3; /bin/true
	@echo "	fnv132 < lltmp2 == 0xce1c9dc5"
	-@./fnv132 < lltmp2 | ${EGREP} -v 0xce1c9dc5; /bin/true
	@echo "	fnv164 < lltmp2 == 0xf8e3e56ce9222325"
	-@./fnv164 < lltmp2 | ${EGREP} -v 0xf8e3e56ce9222325; /bin/true
	@echo "	fnv132 lltmp == 0xb8cbeb33"
	-@./fnv132 lltmp | ${EGREP} -v 0xb8cbeb33; /bin/true
	@echo "	fnv164 lltmp == 0x79dcad190c3291b3"
	-@./fnv164 lltmp | ${EGREP} -v 0x79dcad190c3291b3; /bin/true
	@echo "	fnv132 lltmp2 == 0xce1c9dc5"
	-@./fnv132 lltmp2 | ${EGREP} -v 0xce1c9dc5; /bin/true
	@echo "	fnv164 lltmp2 == 0xf8e3e56ce9222325"
	-@./fnv164 lltmp2 | ${EGREP} -v 0xf8e3e56ce9222325; /bin/true
	@echo "	fnv132 lltmp lltmp == 0x08ae22e5"
	-@./fnv132 lltmp lltmp | ${EGREP} -v 0x08ae22e5; /bin/true
	@echo "	fnv164 lltmp lltmp == 0x10a587a0ff68f305"
	-@./fnv164 lltmp lltmp | ${EGREP} -v 0x10a587a0ff68f305; /bin/true
	@echo "	fnv132 lltmp lltmp2 == 0x23cbeb33"
	-@./fnv132 lltmp lltmp2 | ${EGREP} -v 0x23cbeb33; /bin/true
	@echo "	fnv164 lltmp lltmp2 == 0xcafae19b7f3291b3"
	-@./fnv164 lltmp lltmp2 | ${EGREP} -v 0xcafae19b7f3291b3; /bin/true
	@echo "	fnv132 lltmp2 lltmp == 0x1fcbeb33"
	-@./fnv132 lltmp2 lltmp | ${EGREP} -v 0x1fcbeb33; /bin/true
	@echo "	fnv164 lltmp2 lltmp == 0x06319755db3291b3"
	-@./fnv164 lltmp2 lltmp | ${EGREP} -v 0x06319755db3291b3; /bin/true
	@echo "	fnv132 lltmp2 lltmp2 == 0x1b1c9dc5"
	-@./fnv132 lltmp2 lltmp2 | ${EGREP} -v 0x1b1c9dc5; /bin/true
	@echo "	fnv164 lltmp2 lltmp2 == 0x637a2df54e222325"
	-@./fnv164 lltmp2 lltmp2 | ${EGREP} -v 0x637a2df54e222325; /bin/true
	@echo
	-@rm -f lltmp lltmp2
	@echo "	All done!"
